[package]
name = "rseip-core"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
inlinable_string={version = "^0.1.14", optional = true}

[features]
default = ["feat-inlinable-string"]
feat-inlinable-string= ["inlinable_string"]